services:
  # 1. VERİTABANI (Metrikler ve Parametreler için)
  postgres:
    image: postgres:15
    container_name: rfs_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. DOSYA DEPOLAMA (Artifacts - Modeller için) -> S3 Clon'u
  minio:
    image: minio/minio:latest
    container_name: rfs_minio
    restart: always
    ports:
      - "9000:9000" # API Portu
      - "9001:9001" # Arayüz Portu
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}      # .env dosyasından
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}  # .env dosyasından
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # 2.5. MINIO BUCKET OLUŞTURUCU (Otomatik kova oluşturur)
  create_buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/mlflow-bucket;
      /usr/bin/mc policy set download myminio/mlflow-bucket;
      exit 0;
      "

# 3. DENEY TAKİBİ (MLflow Sunucusu)
  mlflow:
    build: 
      context: ./docker/mlflow
    container_name: rfs_mlflow
    restart: always
    ports:
      - "5001:5000"
    environment:
      # DİKKAT: Artık mlflow_user ve mlflow_db kullanıyor!
      BACKEND_STORE_URI: postgresql+psycopg2://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@postgres:5432/${MLFLOW_DB_NAME}
      
      # MinIO Ayarları (Aynı kalıyor)
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      DEFAULT_ARTIFACT_ROOT: s3://mlflow-bucket/
    command: >
      mlflow server 
      --backend-store-uri postgresql+psycopg2://${MLFLOW_DB_USER}:${MLFLOW_DB_PASSWORD}@postgres:5432/${MLFLOW_DB_NAME} 
      --default-artifact-root s3://mlflow-bucket/ 
      --host 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data: